notifications:
    email: false
language: c++
script:
    - mkdir build/
    - cd build/
    - cmake ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=1 make test
matrix:
    install:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - libsfml-dev
                      - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
