notifications:
    email: false
language: c++
script:
    - mkdir build/
    - cd build/
    - cmake .. -DGCOV=1
    - make
    - CTEST_OUTPUT_ON_FAILURE=1 ctest -V
    - cd ..
    - ./scripts/gen-coverage.sh
after_script:
    - bash <(curl -s https://codecov.io/bash)
before_install:
    - sudo apt-get install libopenal-dev
    - sudo apt-get install libjpeg-dev
    - sudo apt-get install libudev-dev
    - sudo apt-get install libxrandr-dev
    - sudo apt-get install libfreetype6-dev
    - sudo apt-get install libvorbis-dev
    - sudo apt-get install libflac-dev
install:
    #- export CXX=g++-7
    #- export CC=gcc-7
    - git clone https://github.com/SFML/SFML.git
    - cd SFML
    - mkdir build/ && cd build/
    - cmake ..
    - make all
    - sudo make install
    - cd ../..
    - rm -rf SFML
#   addons:
#       apt:
#           sources:
#               - ubuntu-toolchain-r-test
#           packages:
#               - g++-7
