language: cpp

install:
    #- sudo apt-get install -y libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1  libxrandr2 libxrender1 libsoil1
    #- wget http://www.sfml-dev.org/files/SFML-2.3-linux-gcc-64-bit.tar.gz
    #- tar xf SFML-2.3-linux-gcc-64-bit.tar.gz
    #- sudo cp -r SFML-2.3/* /usr/
    #- wget http://mirrors.kernel.org/ubuntu/pool/universe/libs/libsfml/libsfml-dev_2.1+dfsg2-1_amd64.deb
    #- sudo mv libsfml-dev_2.1+dfsg2-1_amd64.deb -t /var/cache/apt/archives
    #- sudo apt-get install libsfml-dev
    - yes | sudo apt-add-repository ppa:sonkun/sfml-stable
    - sudo apt-get update
    - sudo apt-get install libsfml-dev

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest
