language: cpp

install:
    - yes | sudo apt-add-repository ppa:sonkun/sfml-stable
    - sudo apt-get update
    - sudo apt-get install libsfml-dev

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest
