language: cpp

install:
    - sudo add-apt-repository -y ppa:sonkun/sfml
    - sudo apt-get update
    - sudo apt-get install libsfml2-dev

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest
