notifications:
    email: false
language: c++
script:
    - mkdir build/
    - cd build/
    - cmake ..
    - make
    - CTEST_OUTPUT_ON_FAILURE=1 make test
matrix:
    install:
        - os: linux
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - libopenal-dev
                      - libjpeg-dev
                      - libudev-dev
                      - libxrandr-dev
                      - libfreetype6-dev
                      - libvorbis-dev
                      - libflac-dev
                      - g++-7
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
    - git clone https://github.com/SFML/SFML.git
    - cd SFML
    - mkdir build/ && cd build/
    - cmake ..
    - make all
    - sudo make install
